/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReservationsRouteImport } from './routes/api/reservations'
import { Route as ApiTablesAvailableRouteImport } from './routes/api/tables/available'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReservationsRoute = ApiReservationsRouteImport.update({
  id: '/api/reservations',
  path: '/api/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTablesAvailableRoute = ApiTablesAvailableRouteImport.update({
  id: '/api/tables/available',
  path: '/api/tables/available',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/menu': typeof MenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/reservations': typeof ApiReservationsRoute
  '/api/tables/available': typeof ApiTablesAvailableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/menu': typeof MenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/reservations': typeof ApiReservationsRoute
  '/api/tables/available': typeof ApiTablesAvailableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/menu': typeof MenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/reservations': typeof ApiReservationsRoute
  '/api/tables/available': typeof ApiTablesAvailableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/menu'
    | '/sitemap.xml'
    | '/api/reservations'
    | '/api/tables/available'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/menu'
    | '/sitemap.xml'
    | '/api/reservations'
    | '/api/tables/available'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/menu'
    | '/sitemap.xml'
    | '/api/reservations'
    | '/api/tables/available'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MenuRoute: typeof MenuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiReservationsRoute: typeof ApiReservationsRoute
  ApiTablesAvailableRoute: typeof ApiTablesAvailableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reservations': {
      id: '/api/reservations'
      path: '/api/reservations'
      fullPath: '/api/reservations'
      preLoaderRoute: typeof ApiReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tables/available': {
      id: '/api/tables/available'
      path: '/api/tables/available'
      fullPath: '/api/tables/available'
      preLoaderRoute: typeof ApiTablesAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MenuRoute: MenuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiReservationsRoute: ApiReservationsRoute,
  ApiTablesAvailableRoute: ApiTablesAvailableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
